# Site
title: "TotRedus"
description: "Ghidul tau de cumparaturi, calatorii, bani si tehnologie."
meta_description: "Ghidul tau de cumparaturi, calatorii, bani si tehnologie."
logo: 'assets/images/logo-new.webp'
favicon: 'favicon.png'
url: "https://totredus.ro"
google_analytics: 'UA-86031208-5'

sass:
 sass_dir: _sass
 style: compressed

    
# Other
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html

collections:
  reviews:
    output: true     
    permalink: /review/:path/
  new-reviews:
    output: true     
    permalink: /review/:path/
  travel:
    output: true     
    permalink: /travel/:path/
  stiri:
    output: true     
    permalink: /stiri/:path/
  smarthome:
    output: true     
    permalink: /smarthome/:path/
  internet:
    output: true     
    permalink: /internet/:path/
  calculator:
    output: true     
    permalink: /calculator/:path/
  autor:
    output: true     
    permalink: /autor/:path/ 
  manuka:
    output: true     
    permalink: /:path/ 
  categorie:
    output: true     
    permalink: /:path/
  magazine:
    output: true     
    permalink: /:path/
  general:
    output: true     
    permalink: /:path/
  


exclude: ['node_modules']

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

kramdown:
  auto_ids: true

