# Site
name: "TotulRedus"
description: "Haine la super preturi"
meta_description: "Jekyll template, Medium styled, free for bloggers."
logo: 'assets/images/logo.png'
favicon: 'favicon.png'
url: "https://totredus.ro"
google_analytics: 'UA-86031208-5'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

    
# Other
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html



#defaults for product category and pages
defaults:
  -   
    scope:
      path: "_posts/fashion" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "category"
      category: "fashion"