# Site
name: "TotRedus"
description: "Totredus este o platforma ce aduce cele mai mari reduceri intr-un singur loc. Avem o varietate larga de produse. Intra acum!"
meta_description: "Cele mai mari reduceri la o varietate largă de produse."
logo: 'assets/images/log-tr.jpg'
favicon: 'favicon.png'
url: "https://totredus.ro"
google_analytics: 'UA-86031208-5'



    
# Other
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title.html



#defaults for product category and pages
defaults:
  -   
    scope:
      path: "_posts/fashion" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "category"
      category: "fashion"

  -   
    scope:
      path: "_posts/tehnologie" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "category"
      category: "tehnologie"
  -   
    scope:
      path: "_posts/incaltaminte" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "category"
      category: "incaltaminte"	  
  -   
    scope:
      path: "_posts/cosmetice-parfumuri" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "category"
      category: "cosmetice-parfumuri"	  
