# Webfonts (.woff, .woff2, .ttf, etc.)
[[headers]]
  for = "*.woff2"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

[[headers]]
  for = "*.woff"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

[[headers]]
  for = "*.ttf"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

# CSS files
[[headers]]
  for = "*.css"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

# Images (.jpg, .png, .svg, etc.)
[[headers]]
  for = "*.jpg"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

[[headers]]
  for = "*.png"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

[[headers]]
  for = "*.svg"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''

[[headers]]
  for = "*.webp"
  [headers.values]
  cache-control = '''
  max-age=31536000,
  public'''
